name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
    
jobs:
    unit_testing:
        name: unit_testing
        runs-on: ubuntu-latest
        container:
         image: node:20
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

       # - name: Setup NodeJS Version
       #   uses: actions/setup-node@v3
       #   with:
       #     node-version: 20

        - name: Cache NPM Dependencies
          uses: actions/cache@v4
          with:
           path: ~/.npm
           key: '${{ runner.os }}-node-modules-${{ hashFiles(''package-lock.json'') }}'
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml

    code_coverage:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup node JS
        uses: actions/setup-node@v4
        with: 
         node-version: 18
      - run: npm install
      - continue-on-error: true
        run: npm run coverage
      - uses: actions/upload-artifact@v4
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 5

    docker:
     permissions:
      packages: write
     runs-on: ubuntu-latest
     needs: [code_coverage, unit_testing]
     steps:
      - uses: actions/checkout@v4
      - name: Set lowercase repository owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
      - name: docker_login
        uses: docker/login-action@v3
        with:
         username: '${{ github.repository_owner }}'
         password: ${{ secrets.GITHUB_TOKEN }}
         registry: ghcr.io
      - name: docker_build
        uses: docker/build-push-action@v4
        with: 
         context: .
         push: true
         tags: 'ghcr.io/${{ env.REPO_OWNER_LC }}/solar-system:${{ github.sha }}'
        
     
        
        
